Fix pre-commit config
Trailing slash was causing errors on my machine (Ubuntu 18.04, pc 1.12,
git 2.17)

```
[INFO] Initializing environment for https://github.com/python/black/.
An unexpected error has occurred: CalledProcessError: command: ('/usr/bin/git', 'fetch', 'origin', '--tags')
return code: 128
expected return code: 0
stdout: (none)
stderr:
    ERROR: Repository not found.
    fatal: Could not read from remote repository.

    Please make sure you have the correct access rights
    and the repository exists.
```